### ISSUE TITLE
This issue is only used to upload images

### ISSUE THREAD

**Issue by IanBurke1** [ConorTighe1995/Raspberry-Pi-Gesture-App#1]
![rasppi3](https://user-images.githubusercontent.com/22341150/38555690-f7a5ee84-3cbe-11e8-9622-2c7700dcbfc5.jpg)

**Comment by ianburkeixiv** [comment]
![picamera](https://user-images.githubusercontent.com/22341150/38555211-3c6ff70a-3cbd-11e8-87f9-5f3ca1ed5574.jpg)
![rasppi3](https://user-images.githubusercontent.com/22341150/38555212-3c8f1e6e-3cbd-11e8-888e-12a59ff5c754.jpg)

**Comment by IanBurke1** [comment]
![picamera](https://user-images.githubusercontent.com/22341150/38555697-01d20460-3cbf-11e8-9c04-625d9effda03.jpg)

**Comment by ianburkeixiv** [comment]
![rasppi3](https://user-images.githubusercontent.com/22341150/38555272-77d14f42-3cbd-11e8-8503-1c41a119fc5d.jpg)

**Comment by IanBurke1** [comment]
![rasppi3](https://user-images.githubusercontent.com/22341150/38555308-8ee20df2-3cbd-11e8-8750-afe0f8befbc5.jpg)

**Comment by IanBurke1** [comment]
![incorrect](https://user-images.githubusercontent.com/22341150/39085783-e244d4aa-457f-11e8-9219-06fa6c124328.PNG)
![loggedout](https://user-images.githubusercontent.com/22341150/39085784-e267359a-457f-11e8-9913-5c6735c7daca.PNG)
![login](https://user-images.githubusercontent.com/22341150/39085785-e2849c48-457f-11e8-9890-ed2109e804d8.PNG)
![passworduser](https://user-images.githubusercontent.com/22341150/39085786-e2b97274-457f-11e8-96b1-af26d77d4cf6.PNG)

**Comment by IanBurke1** [comment]
![incorrect](https://user-images.githubusercontent.com/22341150/39085836-8f494bc2-4580-11e8-89c8-d85706838c9d.PNG)

**Comment by IanBurke1** [comment]
![sessions](https://user-images.githubusercontent.com/22341150/39085860-04aa195a-4581-11e8-904e-768da53181cc.PNG)

**Comment by IanBurke1** [comment]
![ezgif com-resize 4](https://user-images.githubusercontent.com/22341150/39207167-2ec1439e-47f7-11e8-9bcd-a94138763449.gif)
![ezgif com-resize 3](https://user-images.githubusercontent.com/22341150/39207168-2ee94150-47f7-11e8-9311-4a32405647c1.gif)

**Comment by IanBurke1** [comment]
![bgesture](https://user-images.githubusercontent.com/22341150/39207569-3308e366-47f8-11e8-9c9c-81453041d3f4.png)
![gesture](https://user-images.githubusercontent.com/22341150/39207570-332acb2a-47f8-11e8-9527-cab3fda36b26.png)
![gestureb](https://user-images.githubusercontent.com/22341150/39207572-3348bd42-47f8-11e8-9455-20700d62d9e7.png)

**Comment by IanBurke1** [comment]
![architect](https://user-images.githubusercontent.com/22341150/39208148-07ab5fa8-47fa-11e8-8799-88fe0af5432d.PNG)
